language: python
python:
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install poetry
install:
- poetry install
- pip install coveralls pytest-cov
script: pytest --cov=arcade_gui
after_success: coveralls