globals:
  font_color: BLACK

label:
  font_size: 12
  font_color: BLACK


flatbutton:
#  font_color: BLACK

  normal_color: 25A258
  hover_color: 26C06D
  pressed_color: 1E7339

ghostflatbutton:
#  font_color: BLACK

  normal_color: 25A258
  hover_color: 2BA24E
  pressed_color: 1E7339

inputbox:
#  font_color: BLACK

  normal_color: BLACK
  shadow_color: WHITE_SMOKE
  highlight_color: WHITE